source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'WhatEat' do
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'AFNetworking', '3.2.1'
    pod 'SDWebImage', '~> 5.0.0-beta2'
    pod 'Masonry', '1.1.0'
    pod 'YYCache', '1.0.4'
    pod 'Bugly', '2.5.0'
    pod 'MJRefresh', '3.1.15.3'
end
